# Generated by Django 5.0 on 2025-11-26 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestorProductos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Antiparasitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('tipo', models.CharField(choices=[('antiparasitario', 'Antiparasitario'), ('otros', 'Otros')], default='otros', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='medicamento',
            name='imagen',
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='tipo',
            field=models.CharField(choices=[('vitamina', 'Vitamina'), ('otros', 'Otros')], default='otros', max_length=50),
        ),
    ]
