# Generated by Django 5.0 on 2025-11-25 20:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestorUser', '0004_add_titular_to_citamedica'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='citamedica',
            unique_together={('user', 'fecha', 'hora')},
        ),
    ]
