# Generated by Django 5.0 on 2025-11-26 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestorUser', '0005_alter_citamedica_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citamedica',
            name='tipo_mascota',
            field=models.CharField(choices=[('gato', 'Gato'), ('perro', 'Perro'), ('ave', 'Ave'), ('conejo', 'Conejo'), ('hamster', 'Hamster'), ('otro', 'Otro')], default='otro', max_length=10),
        ),
    ]
