from django.urls import path
from .views import (
    home, vetInicio, logout_view, datatable, datatable2, datatable3, datatable4,
    sobreData, alimentoPerroAData, alimentoPerroCData, alimentoPerroSData, antipulgasData,
    alimentoGatoAData, alimentoGatoCData, Snack_gato, Snack_Perro,
    medicamentos, shampoos, camas, collares, juguetes,
    ver_carrito, agregar_carrito, actualizar_carrito, eliminar_carrito,
    api_perros_adulto, api_perros_cachorro, api_perros_senior, api_perros_snacks,
    api_gatos_adulto, api_gatos_cachorro, api_gatos_snacks,
    api_antiparasitario, api_shampoo, api_medicamento, api_collares, api_camas, api_juguetes,
    api_aproductos, agregar_producto,
    crear_alimentopa, crear_alimentopc, crear_alimentops, crear_snackp,
    crear_alimentoga, crear_alimentogc, crear_snackg,
    crear_antiparasitario, crear_shampoo, crear_medicamentos, crear_collares, crear_camas, crear_juguetes,
    ProductoPCRegistro, ProductoPARegistro, ProductoPSRegistro, AProductoRegistro,
    SnackPerroRegistro, AlimentoGARegistro, AlimentoGCRegistro, SnackGatoRegistro,
    antiparasitarioRegistro, shampooRegistro, medicamentosRegistro,
    collaresRegistro, camasRegistro, juguetesRegistro,
    editarProducto, editarProductoPA, editarProductoPC, editarProductoPS, editarProductoA,
    editarProductoAGA, editarProductoAGC, editarProductoSnackG, editarProductoSnackP,
    editarProductoAntiparasitario, editarProductoMedicamento, editarProductoShampoo,
    editarProductoCollar, editarProductoCama, editarProductoJuguete,
    eliminarProducto, eliminarProductoPA, eliminarProductoPC, eliminarProductoPS, eliminarProductoA,
    eliminarProductoAGA, eliminarProductoAGC, eliminarProductoSnackG, eliminarProductoSnackP,
    eliminarProductoAntiparasitario, eliminarProductoMedicamento, eliminarProductoShampoo,
    eliminarProductoCollar, eliminarProductoCama, eliminarProductoJuguete,antiparasitarios,
    guardar_producto
)

urlpatterns = [
    # Home and main pages
    path('', home, name='home'),
    path('vet_inicio/', vetInicio, name='vet_inicio'),
    path('logout/', logout_view, name='logout'),
    path('sobreNosotros/', sobreData, name='sobre_nosotros'),
    path('alimento-perro-adulto/', alimentoPerroAData, name='perro_adulto'),
    path('alimento-perro-cachorro/', alimentoPerroCData, name='perro_cachorro'),
    path('alimento-perro-senior/', alimentoPerroSData, name='perro_senior'),
    path('antipulgas/', antipulgasData, name='antipulgas'),
    path('alimento-gato-adulto/', alimentoGatoAData, name='gato_adulto'),
    path('alimento-gato-cachorro/', alimentoGatoCData, name='gato_cachorro'),
    path('snack-gato/', Snack_gato, name='snack_gato'),
    path('snack-perro/', Snack_Perro, name='snack_perro'),
    path('medicamentos/', medicamentos, name='medicamentos'),
    path('shampoos/', shampoos, name='shampoos'),
    path('camas/', camas, name='camas'),
    path('collares/', collares, name='collares'),
    path('juguetes/', juguetes, name='juguetes'),
    path('antiparasitario/', antiparasitarios, name='antiparasitario'),

#DATATABLE:
    path('datatable/', datatable, name='datatable'),
    path('datatable2/', datatable2, name='datatable2'),
    path('datatable3/', datatable3, name='datatable3'),
    path('datatable4/', datatable4, name='datatable4'),

    # API endpoints for DataTables
    path('api/perros/adulto/', api_perros_adulto, name='api_perro_adulto'),
    path('api/perros/cachorro/', api_perros_cachorro, name='api_perro_cachorro'),
    path('api/perros/senior/', api_perros_senior, name='api_perro_senior'),
    path('api/perros/snacks/', api_perros_snacks, name='api_perros_snacks'),
    path('api/gatos/adulto/', api_gatos_adulto, name='api_gato_adulto'),
    path('api/gatos/cachorro/', api_gatos_cachorro, name='api_gato_cachorro'),
    path('api/gatos/snacks/', api_gatos_snacks, name='api_gatos_snacks'),
    path('api/antiparasitario/', api_antiparasitario, name='api_antiparasitario'),
    path('api/shampoo/', api_shampoo, name='api_shampoo'),
    path('api/medicamento/', api_medicamento, name='api_medicamento'),
    path('api/collares/', api_collares, name='api_collares'),
    path('api/camas/', api_camas, name='api_camas'),
    path('api/juguetes/', api_juguetes, name='api_juguetes'),
    path('api/aproductos/', api_aproductos, name='api_aproductos'),

    # Create product forms
    path('crear/alimentopa/', crear_alimentopa, name='crear_alimentopa'),
    path('crear/alimentopc/', crear_alimentopc, name='crear_alimentopc'),
    path('crear/alimentops/', crear_alimentops, name='crear_alimentops'),
    path('crear/snackp/', crear_snackp, name='crear_snackp'),
    path('crear/alimentoga/', crear_alimentoga, name='crear_alimentoga'),
    path('crear/alimentogc/', crear_alimentogc, name='crear_alimentogc'),
    path('crear/snackg/', crear_snackg, name='crear_snackg'),
    path('crear/antiparasitario/', crear_antiparasitario, name='crear_antiparasitario'),
    path('crear/shampoo/', crear_shampoo, name='crear_shampoo'),
    path('crear/medicamentos/', crear_medicamentos, name='crear_medicamentos'),
    path('crear/collares/', crear_collares, name='crear_collares'),
    path('crear/camas/', crear_camas, name='crear_camas'),
    path('crear/juguetes/', crear_juguetes, name='crear_juguetes'),

    # Registro views
    path('producto-pc-registro/', ProductoPCRegistro, name='producto_pc_registro'),
    path('producto-pa-registro/', ProductoPARegistro, name='producto_pa_registro'),
    path('producto-ps-registro/', ProductoPSRegistro, name='producto_ps_registro'),
    path('aproducto-registro/', AProductoRegistro, name='aproducto_registro'),
    path('snack-perro-registro/', SnackPerroRegistro, name='snack_perro_registro'),
    path('alimento-ga-registro/', AlimentoGARegistro, name='alimento_ga_registro'),
    path('alimento-gc-registro/', AlimentoGCRegistro, name='alimento_gc_registro'),
    path('snack-gato-registro/', SnackGatoRegistro, name='snack_gato_registro'),
    path('snackgato_registro/', SnackGatoRegistro, name='snackgato_registro'),
    path('antiparasitario_registro/', antiparasitarioRegistro, name='antiparasitario_registro'),
    path('shampoo_registro/', shampooRegistro, name='shampoo_registro'),
    path('medicamentos_registro/', medicamentosRegistro, name='medicamentos_registro'),
    path('collares_registro/', collaresRegistro, name='collares_registro'),
    path('camas_registro/', camasRegistro, name='camas_registro'),
    path('juguetes_registro/', juguetesRegistro, name='juguetes_registro'),

    # Cart views
    path('carrito/', ver_carrito, name='ver_carrito'),
    path('carrito/agregar/<str:tipo>/<int:producto_id>/', agregar_carrito, name='agregar_carrito'),
    path('carrito/actualizar/', actualizar_carrito, name='actualizar_carrito'),
    path('carrito/eliminar/<str:tipo>/<int:producto_id>/', eliminar_carrito, name='eliminar_carrito'),

    # Edit and delete product views
    path('editar/<int:id>/', editarProducto, name='editarProducto'),
    path('eliminar/<int:codigo>/', eliminarProducto, name='eliminarProducto'),
    path('editar/pa/<str:codigo>/', editarProductoPA, name='editarProductoPA'),
    path('eliminar/pa/<str:codigo>/', eliminarProductoPA, name='eliminarProductoPA'),
    path('editar/pc/<str:codigo>/', editarProductoPC, name='editarProductoPC'),
    path('eliminar/pc/<str:codigo>/', eliminarProductoPC, name='eliminarProductoPC'),
    path('editar/ps/<str:codigo>/', editarProductoPS, name='editarProductoPS'),
    path('eliminar/ps/<str:codigo>/', eliminarProductoPS, name='eliminarProductoPS'),
    path('editar/a/<str:codigo>/', editarProductoA, name='editarProductoA'),
    path('eliminar/a/<str:codigo>/', eliminarProductoA, name='eliminarProductoA'),
    path('editar/aga/<str:codigo>/', editarProductoAGA, name='editarProductoAGA'),
    path('eliminar/aga/<str:codigo>/', eliminarProductoAGA, name='eliminarProductoAGA'),
    path('editar/agc/<str:codigo>/', editarProductoAGC, name='editarProductoAGC'),
    path('eliminar/agc/<str:codigo>/', eliminarProductoAGC, name='eliminarProductoAGC'),
    path('editar/snackg/<str:codigo>/', editarProductoSnackG, name='editarProductoSnackG'),
    path('eliminar/snackg/<str:codigo>/', eliminarProductoSnackG, name='eliminarProductoSnackG'),
    path('editar/snackp/<str:codigo>/', editarProductoSnackP, name='editarProductoSnackP'),
    path('eliminar/snackp/<str:codigo>/', eliminarProductoSnackP, name='eliminarProductoSnackP'),
    path('editar/antiparasitario/<str:codigo>/', editarProductoAntiparasitario, name='editarProductoAntiparasitario'),
    path('eliminar/antiparasitario/<str:codigo>/', eliminarProductoAntiparasitario, name='eliminarProductoAntiparasitario'),
    path('editar/medicamento/<str:codigo>/', editarProductoMedicamento, name='editarProductoMedicamento'),
    path('eliminar/medicamento/<str:codigo>/', eliminarProductoMedicamento, name='eliminarProductoMedicamento'),
    path('editar/shampoo/<str:codigo>/', editarProductoShampoo, name='editarProductoShampoo'),
    path('eliminar/shampoo/<str:codigo>/', eliminarProductoShampoo, name='eliminarProductoShampoo'),
    path('editar/collar/<str:codigo>/', editarProductoCollar, name='editarProductoCollar'),
    path('eliminar/collar/<str:codigo>/', eliminarProductoCollar, name='eliminarProductoCollar'),
    path('editar/cama/<str:codigo>/', editarProductoCama, name='editarProductoCama'),
    path('eliminar/cama/<str:codigo>/', eliminarProductoCama, name='eliminarProductoCama'),
    path('editar/juguete/<str:codigo>/', editarProductoJuguete, name='editarProductoJuguete'),
    path('eliminar/juguete/<str:codigo>/', eliminarProductoJuguete, name='eliminarProductoJuguete'),

    # Other
    path('guardar-producto/', guardar_producto, name='guardar_producto'),
    path('agregar-producto/', agregar_producto, name='agregar_producto'),
]
